### ISSUE TITLE
Daftar menu  dan harga satuan disimpan di CSV

### ISSUE THREAD

**Issue by priyandari** [pascalefraim/KASIR#3]
Bisa dilakukan :
penambahan menu
Edit menu dan harga
hapus menu

**Comment by zatimi** [comment]
daftar menu dan harga satuan sudah disimpan di file csv, untuk penambahan menu sudah dapat dilakukan, namun untuk edit menu serta harga dan hapus menu dapat dilakukan dengan mengedit file csvnya..

**Comment by priyandari** [comment]
Ok
